const SourceType = {
    LINK: "LINK",
    PODCASTS_APPLE: "PODCASTS_APPLE",
    PODCASTS_GOOGLE: "PODCASTS_GOOGLE",
    PODCASTS_POCKETCASTS: "PODCASTS_POCKETCASTS",
    PODCASTS_CASTBOX: "PODCASTS_CASTBOX",
    BOOK: "BOOK",
    VIDEO: "VIDEO"
}

export default SourceType;