// Monument
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const CHANGE_CENCEL_REQUEST = "CHANGE_CENCEL_REQUEST";
export const FETCH_MONUMENTS_LOADING_END = "FETCH_MONUMENTS_LOADING_END";
// Filter
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const CHANGE_STATUSES = "CHANGE_STATUSES";
export const CHANGE_CONDITIONS = "CHANGE_CONDITIONS";
export const CHANGE_CITIES = "CHANGE_CITIES";
export const CHANGE_YEARS_RANGE = "CHANGE_YEARS_RANGE";
// Map
export const CHANGE_CENTER = "CHANGE_CENTER";
// Detail Monument
export const OPEN_DETAIL_DRAWER = "OPEN_DETAIL_DRAWER";
export const CLOSE_DETAIL_DRAWER = "CLOSE_DETAIL_DRAWER";
export const CHANGE_SELECTED_MONUMENT = "CHANGE_SELECTED_MONUMENT";