// Monument
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const FETCH_MONUMENTS_LOADING_END = "FETCH_MONUMENTS_LOADING_END";