// Monument
export const FETCH_MONUMENTS_REQUEST = 'FETCH_MONUMENTS_REQUEST';
export const FETCH_MONUMENTS_SUCCESS = "FETCH_MONUMENTS_SUCCESS";
export const FETCH_MONUMENTS_FAILURE = "FETCH_MONUMENTS_FAILURE";
export const FETCH_MONUMENTS_LOADING_END = "FETCH_MONUMENTS_LOADING_END";
// Filter
export const OPEN_DRAWER = "OPEN_DRAWER";
export const CLOSE_DRAWER = "CLOSE_DRAWER";
export const CHANGE_STATUSES = "CHANGE_STATUSES";
export const CHANGE_CONDITIONS = "CHANGE_CONDITIONS";
export const CHANGE_CITIES = "CHANGE_CITIES";
export const CHANGE_YEARS_RANGE = "CHANGE_YEARS_RANGE";